#!/usr/bin/python3

import sys
import musicpd 
import argparse
import util
import config_file

def parse_args ():
    parser = argparse.ArgumentParser ()
    parser.add_argument ('-p', '--play', nargs = '?', default = False,
            help='toggle play, input number to play song in playlist')
    parser.add_argument ('--pause', nargs = '?', default = False,
            help='toggle pause')
    parser.add_argument ('-n', '--next', action="store_true", default=False,
            help='play next track')
    parser.add_argument ('-ps', '--previous', '--prev', action="store_true", default=False,
            help='play previous track')
    parser.add_argument ('--stop', action="store_true", default=False,
            help='stop playback')
    parser.add_argument ('--random', nargs = '?', default = False,
            help='random [on,off]')
    parser.add_argument ('-u', '--update', action="store_true", default = False,
            help='update mpd database') 
    parser.add_argument ('-a', '--add', action="store_true", default=False,
            help='add songs to playlist, useful to receive piped input from shell')
    parser.add_argument ('-s', '--search', type = str, nargs = '?', default = False,
            help='search a string in the database, casi insensitive')
    parser.add_argument ('-f', '--filter', nargs = '+', default = False,
            help='filter search result, can use \'artist\', \'album\', \'title\', grep like functionality')
    parser.add_argument ('-nf', '--no-filter', nargs = '+', default = False,
            help='filter search result excluding matching, can use \'artist\', \'album\', \'title\', grep -n like functionality')
    parser.add_argument ('--clear', action = "store_true", default=False,
            help='clear playlist')
    parser.add_argument ('-pl', '--playlist', action = "store_true", default=False,
            help='show playlist')
    parser.add_argument ('--seek', nargs='?', default=False,
            help='seek current track: works by seconds or by percentage ')
    parser.add_argument ('--shuffle', action = "store_true", default=False,
            help='shuffle playlist')
    parser.add_argument ('--consume', nargs = '?', default=False,
            help='consume mode [on,off]')
    parser.add_argument ('--single', nargs = '?', default=False,
            help='single mode [on,off]')
    parser.add_argument ('--swap', nargs = 2, default=False,
            help='swap two tracks in the playlist')
    parser.add_argument ('--format', nargs= '+', default = False,
                         help='change display format, write \'kpd --format help\' for usage')
    parser.add_argument ('--output', action = "store_true", default = False,
                         help='print output on screen, default enabled')
    parser.add_argument ('--no-output', action = "store_true", default = False,
                         help='do not print output on screen')

    args = parser.parse_args ()
    dictArgs = vars (args)

    return args, dictArgs
#end parse_args

def order_args (argv):
    argsDict1 = {'-h':'help', '-p':'play', '-n':'next', '-u':'update', '-s':'search', '-f':'filter', '-pl':'playlist', '-a':'add'}
    argsDict2 = {'--help':'help', '--play':'play', '--next':'next', '--update':'update', '--search':'search', '--filter':'filter', '--playlist':'playlist', \
                 '--stop':'stop', '--random':'random', '--clear':'clear', '--seek':'seek', '--shuffle':'shuffle', '--consume':'consume', '--single':'single','--swap':'swap',\
                 '--prev':'previous', '--previous':'previous', '--add':'add', '--output':'output', '--no-output':'no_output', '--pause':'pause',\
                 '--format':'format', '--no-filter':'nofilter'}
    argsOrder = list ()
    for el in argv:
        if el in argsDict1:
            argsOrder.append (argsDict1[el])
        if el in argsDict2:
            argsOrder.append (argsDict2[el])
    return argsOrder

if __name__ == '__main__':

    DBlocation, host, port = config_file.parse_file ()
    argsOrder = order_args (sys.argv)
    args, dictArgs = parse_args ()
    client = util.mpdclient (DBlocation, host, port, args.filter, args.no_filter)

## no args
    if not len (sys.argv) > 1:
        if  client.status['state'] != 'stop':
            util.current_status (client)
        else:
            util.playlist (client, None, None)
        exit ()

# pipe from shell
    if not sys.stdin.isatty() and args.add != False:
        for line in sys.stdin:
            line = line.rstrip ('\n')
            client.client.add (line)
        exit ()
# end pipe from shell

# evaluate arguments if not pipe
    searchRes = None
    retUtil = None

    for el in argsOrder:
        if dictArgs[el] != False:
            client.update_status ()
            methodToCall = getattr (util, el)
            retUtil = methodToCall (client, dictArgs[el], searchRes)

            if retUtil != None: #the only alternative is a return null in every funct
                searchRes = retUtil
