.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "KPD" "1" "September 2016" "" ""
.
.SH "NAME"
\fBkpd\fR \- client for Music Player Daemon (MPD)
.
.SH "SYNOPSIS"
\fBkpd\fR \fIoptions\fR [\fIargument\fR] \fIoptions\fR [\fIargument\fR] \.\.\. \.\.\.
.
.SH "DESCRIPTION"
\fBkpd\fR is a client for MPD, the Music Player Daemon\. kpd connects to a MPD istance ad controls it according to commands issued\. If no command is given, the current status is printed\.
.
.SH "OPTIONS"
\fB\-V, \-\-verbose\fR \fIon|off\fR
.
.IP "" 4
.
.nf

Enable or disable output on screen
.
.fi
.
.IP "" 0
.
.P
\fB\-\-host\fR
.
.IP "" 4
.
.nf

The host to connect to\. If not given `kpd` will use the value set on `settings\.h`
.
.fi
.
.IP "" 0
.
.P
\fB\-\-port\fR
.
.IP "" 4
.
.nf

The port to connect to\. If not given `kpd` will use the value set on `settings\.h`
.
.fi
.
.IP "" 0
.
.P
\fB\-a, \-\-add\fR
.
.IP "" 4
.
.nf

Add a song from the search results to the playlist\. Can also read input from pipes\. Doesn\'t accept arguments\.
.
.fi
.
.IP "" 0
.
.P
\fB\-\-clear\fR
.
.IP "" 4
.
.nf

Empties the playlist
.
.fi
.
.IP "" 0
.
.P
\fB\-\-consume\fR \fIon|off|true|false|0|1\fR
.
.IP "" 4
.
.nf

Toggle consume mode if state is not specified
.
.fi
.
.IP "" 0
.
.P
\fBdelete\fR Aspettando Galla
.
.P
\fBdelete range\fR Aspettando Galla
.
.P
\fB\-h, \-\-help\fR
.
.IP "" 4
.
.nf

Show help
.
.fi
.
.IP "" 0
.
.P
\fB\-l, \-\-list\fR
.
.IP "" 4
.
.nf

Prints entire playlist
.
.fi
.
.IP "" 0
.
.P
\fB\-n, \-\-next\fR
.
.IP "" 4
.
.nf

Starts playing next song
.
.fi
.
.IP "" 0
.
.P
\fB\-P, \-\-pause\fR
.
.IP "" 4
.
.nf

Pauses playing
.
.fi
.
.IP "" 0
.
.P
\fB\-p, \-\-play\fR \fIposition\fR
.
.IP "" 4
.
.nf

Starts playing the song on playlist specified by the number\. If no position is specified, toggles play
.
.fi
.
.IP "" 0
.
.P
\fB\-b, \-\-prev, \-\-previous\fR
.
.IP "" 4
.
.nf

Starts playing previous song on playlist
.
.fi
.
.IP "" 0
.
.P
\fB\-\-random\fR \fIon|off|true|false|0|1\fR
.
.IP "" 4
.
.nf

Toggle random mode if state is not specified
.
.fi
.
.IP "" 0
.
.P
\fB\-\-repeat\fR \fIon|off|true|false|0|1\fR
.
.IP "" 4
.
.nf

Toggle repeat mode if state is not specified
.
.fi
.
.IP "" 0
.
.P
\fB\-S, \-\-stop\fR
.
.IP "" 4
.
.nf

Stops playing
.
.fi
.
.IP "" 0
.
.P
\fB\-\-seek\fR Aspettando Eug
.
.P
\fB\-\-single\fR \fIon|off|true|false|0|1\fR
.
.IP "" 4
.
.nf

Toggle single mode if state is not specified
.
.fi
.
.IP "" 0
.
.P
\fB\-\-shuffle\fR
.
.IP "" 4
.
.nf

Shuffles all songs on the playlist
.
.fi
.
.IP "" 0
.
.P
\fB\-\-swap\fR Aspettando Gab
.
.P
\fB\-\-update\fR
.
.IP "" 4
.
.nf

Scans music directory for updates
.
.fi
.
.IP "" 0
.
.P
\fB\-V, \-\-verbose\fR \fIon|off|true|false|0|1\fR
.
.IP "" 4
.
.nf

Disable (redirect to /dev/null) or enable output\. The state must be specified
.
.fi
.
.IP "" 0
.
.SH "RETURN VALUES"
.
.SH "BUGS"
Report bugs to me@francescomecca\.eu
.
.SH "AUTHOR"
Eugenio Corso, Gabriele Corso, Francesco Galla, Francesco Mecca
